# Generated by Django 2.2.16 on 2020-09-24 12:13

import champion.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('champion', djongo.models.fields.EmbeddedField(model_container=champion.models.Champion)),
            ],
        ),
    ]
